import os
import yaml
from pathlib import Path
from datetime import datetime
from src.models import ProjectContext, Mission

class ProjectScaffold:
    def __init__(self, base_path: str = "projects"):
        self.base_path = base_path

    def create_structure(self, context: ProjectContext) -> str:
        """
        Creates the folder structure for a new project.
        Returns the absolute path to the project root.
        """
        # Sanitize project name for folder
        safe_name = context.project_name.replace(" ", "_").replace("/", "-")
        year = datetime.now().strftime("%Y")
        
        # Structure: projects/{Year}/{Project_Name}
        project_root = Path(self.base_path) / year / safe_name
        
        # Subdirectories
        subdirs = [
            "00_Intake",
            "01_Strategy",
            "02_Design",
            "03_Finance",
            "99_Delivery"
        ]
        
        for subdir in subdirs:
            (project_root / subdir).mkdir(parents=True, exist_ok=True)
            
        return str(project_root)

    def inject_mission(self, project_root: str, mission: Mission):
        """
        Writes the .antigravity/mission file to the project root.
        """
        mission_dir = Path(project_root) / ".antigravity"
        mission_dir.mkdir(exist_ok=True)
        
        mission_file = mission_dir / "mission"
        
        mission_data = mission.model_dump()
        
        # Convert context to dict for YAML serialization
        if hasattr(mission_data['context'], 'model_dump'):
             mission_data['context'] = mission_data['context'].model_dump()
             
        with open(mission_file, "w") as f:
            yaml.dump(mission_data, f, default_flow_style=False)

class ProposalGenerator:
    def generate(self, context: ProjectContext) -> str:
        """
        Generates the content for the Initial Proposal artifact.
        """
        deliverables_list = "\n".join([f"- {d}" for d in context.deliverables])
        deadlines_list = "\n".join([f"- **{k}**: {v}" for k, v in context.hard_deadlines.items()])
        
        return f"""# Initial Proposal: {context.project_name}

## Executive Summary
We have received your request and are excited to partner with you. 
**Goal**: {', '.join(context.client_goals)}

## Scope of Work
The following deliverables have been identified:
{deliverables_list}

## Timeline
We are committed to the following milestones:
{deadlines_list}

## Investment
**Estimated Budget**: {context.budget_hint or "To be determined based on detailed scoping."}

---
*Generated by Antigravity Studio Intake Agent*
"""
