from typing import Dict, Any
from pathlib import Path
from src.shared.bank import StudioBank, COST_TABLE # type: ignore
from src.shared.logger import AgentLogger # type: ignore

def motion_choreographer_agent(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Motion Intelligence Agent
    Role: Defines Rhythm, Pacing, and Animation Guardrails.
    Provides the temporal blueprint for the human motion designer.
    """
    project_id = state.get("project_id", 1)
    logger = AgentLogger(project_id)
    
    logger.log("Motion Choreographer", "Defining Motion Guardrails...")
    
    # Logic: Define Motion Principles
    project_name = state.get("project_name", "Untitled")
    safe_name = project_name.replace(" ", "_").replace("/", "-")
    proj_root = Path("projects") / "2026" / safe_name
    delivery_dir = proj_root / "99_Delivery"
    delivery_dir.mkdir(parents=True, exist_ok=True)
    
    motion_intel = {
        "rhythm_and_pacing": [
            "Start with high-energy impact, then decelerate into details",
            "Maintain a 'Breathing' rhythm: 2s focus, 0.5s transition",
            "Align transitions with the custom brand soundscape (to be produced by human)"
        ],
        "animation_principles": [
            "Ease-in/Ease-out with custom bezier curves (0.4, 0, 0.2, 1)",
            "No linear movement. Everything must feel organic/premium",
            "Focus on 'Blur-to-Focus' reveals for luxury objects"
        ],
        "eval_checklist": [
            "Does the motion feel heavy and expensive, or light and fast?",
            "Is the hierarchy preserved during complex transitions?",
            "Does the motion support or distract from the core brand message?"
        ]
    }
    
    # Local Persistence
    intel_file = delivery_dir / "Motion_Intelligence.md"
    content = f"""# Motion Intelligence: {project_name}

## ⏱️ Rhythm & Pacing
- {"\n- ".join(motion_intel['rhythm_and_pacing'])}

## 🎞️ Animation Principles
- {"\n- ".join(motion_intel['animation_principles'])}

## ⚖️ Motion Evaluation
- {"\n- ".join(motion_intel['eval_checklist'])}

---
*Generated by Templo Atelier Motion Intelligence Agent v9.0*
"""
    with open(intel_file, "w") as f:
        f.write(content)
        
    logger.log("Motion Choreographer", "Motion guardrails established locally.")

    # Mirror to Drive
    try:
        from src.shared.drive_utils import get_drive_service, find_folder, ensure_folder, upload_file  # type: ignore
        drive = get_drive_service()
        root_id = find_folder(drive, "Templo Atelier")
        projects_id = find_folder(drive, "05_Projects", root_id)
        project_folder_id = find_folder(drive, project_name, projects_id)
        
        if project_folder_id:
            delivery_folder_id = ensure_folder(drive, "99_Delivery", project_folder_id)
            upload_file(drive, str(intel_file), delivery_folder_id)
            logger.log("Motion Choreographer", "Motion intelligence mirrored to Google Drive.")
    except Exception as e:
        logger.log("Motion Choreographer", f"Drive sync failed: {e}", severity="WARN")

    return {"motion_intel_path": str(intel_file)}
