from typing import Dict, Any
from pathlib import Path
from src.shared.logger import AgentLogger # type: ignore

def social_growth_agent(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    Content Intelligence Agent
    Role: Defines Tone of Voice and Campaign Guardrails.
    Provides the strategic boundaries for the human content creator.
    """
    project_id = state.get("project_id", 1)
    logger = AgentLogger(project_id)
    
    logger.log("Social Growth", "Defining Content Guardrails...")
    
    # Logic: Define Platform Guardrails
    project_name = state.get("project_name", "Untitled")
    safe_name = project_name.replace(" ", "_").replace("/", "-")
    proj_root = Path("projects") / "2026" / safe_name
    delivery_dir = proj_root / "99_Delivery"
    delivery_dir.mkdir(parents=True, exist_ok=True)
    
    content_intel = {
        "tone_boundaries": [
            "Confident but never arrogant",
            "Witty but not slapstick",
            "Direct and information-rich"
        ],
        "platform_constraints": [
            "Instagram: Visual-first, zero-fluff captions",
            "LinkedIn: Thought-leadership focused, no hashtags",
            "X: Real-time industry commentary"
        ],
        "eval_checklist": [
            "Does this stop the scroll for our specific psychographic?",
            "Is the CTA clear and singular?",
            "Does it align with the 'Transparent Luxury' strategic pillar?"
        ]
    }
    
    # Local Persistence
    intel_file = delivery_dir / "Content_Intelligence.md"
    content = f"""# Content Intelligence: {project_name}

## 🗣️ Tone of Voice Boundaries
- {"\n- ".join(content_intel['tone_boundaries'])}

## 🏟️ Platform Constraints
- {"\n- ".join(content_intel['platform_constraints'])}

## ⚖️ Campaign Evaluation
- {"\n- ".join(content_intel['eval_checklist'])}

---
*Generated by Templo Atelier Content Intelligence Agent v9.0*
"""
    with open(intel_file, "w") as f:
        f.write(content)
        
    logger.log("Social Growth", "Content guardrails established locally.")

    # Mirror to Drive
    try:
        from src.shared.drive_utils import get_drive_service, find_folder, ensure_folder, upload_file  # type: ignore
        drive = get_drive_service()
        root_id = find_folder(drive, "Templo Atelier")
        projects_id = find_folder(drive, "05_Projects", root_id)
        project_folder_id = find_folder(drive, project_name, projects_id)
        
        if project_folder_id:
            delivery_folder_id = ensure_folder(drive, "99_Delivery", project_folder_id)
            upload_file(drive, str(intel_file), delivery_folder_id)
            logger.log("Social Growth", "Content intelligence mirrored to Google Drive.")
    except Exception as e:
        logger.log("Social Growth", f"Drive sync failed: {e}", severity="WARN")

    return {"content_intel_path": str(intel_file)}
