from typing import Dict, Any
from pathlib import Path
from src.shared.bank import StudioBank, COST_TABLE # type: ignore
from src.shared.logger import AgentLogger # type: ignore
from src.shared.db import ProjectOS # type: ignore

def ui_architect_agent(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    UX Architect Agent
    Role: Defines Information Architecture and UX Guardrails.
    Provides the structural blueprint for the human designer.
    """
    project_id = state.get("project_id", 1)
    logger = AgentLogger(project_id)
    
    logger.log("UI Architect", "Defining UX Architecture & IA...")
    
    # 1. Budget check
    budget = state.get("project_budget_tokens", 0)
    bank = StudioBank(budget)
    cost = COST_TABLE["image_flux_pro"] # Symbolic cost for architecture synthesis
    
    if not bank.check_funds(cost):
        return {"project_status": "Paused: Budget Exceeded"}
    
    # 2. Logic: Define IA & Guardrails
    project_name = state.get("project_name", "Untitled")
    safe_name = project_name.replace(" ", "_").replace("/", "-")
    proj_root = Path("projects") / "2026" / safe_name
    design_dir = proj_root / "02_Design"
    design_dir.mkdir(parents=True, exist_ok=True)
    
    ux_architecture = {
        "ia_structure": [
            "Home: Brand Narrative -> Feature Tease -> Conversion",
            "Portfolio: Selection Logic -> High-Impact Detail -> Direct Inquiry",
            "Contact: Frictionless Intake -> Data Capture -> Instant Acknowledge"
        ],
        "ux_principles": [
            "Zero Friction: Minimize clicks to core value",
            "Predictive Navigation: User should never wonder 'where am I?'",
            "Mobile-Exquisite: Design for high-end mobile experience first"
        ],
        "interaction_guardrails": [
            "Use subtle micro-interactions for feedback only",
            "Avoid aggressive scroll-jacking",
            "Privacy-first form design"
        ]
    }
    
    # Local Persistence
    arch_file = design_dir / "UX_Architecture.md"
    content = f"""# UX Architecture: {project_name}

## 🏗️ Information Architecture (IA)
- {"\n- ".join(ux_architecture['ia_structure'])}

## 🧭 UX Principles
- {"\n- ".join(ux_architecture['ux_principles'])}

## 🛡️ Interaction Guardrails
- {"\n- ".join(ux_architecture['interaction_guardrails'])}

---
*Generated by Templo Atelier UX Architect Agent v9.0*
"""
    with open(intel_file, "w") as f:
        f.write(content)
        
    logger.log("UI Architect", "UX Architecture established locally.", cost=cost)

    # --- Real-Time OS Sync ---
    ProjectOS.update_intelligence(project_id, "timeline", ux_architecture["ia_structure"]) # IA maps to timeline/structure # type: ignore
    ProjectOS.update_status(project_id, "UI Architect", "UX Architecture Established") # type: ignore

    new_budget = budget - cost

    # 3. Mirror to Drive
    try:
        from src.shared.drive_utils import get_drive_service, find_folder, ensure_folder, upload_file  # type: ignore
        drive = get_drive_service()
        root_id = find_folder(drive, "Templo Atelier")
        projects_id = find_folder(drive, "05_Projects", root_id)
        project_folder_id = find_folder(drive, project_name, projects_id)
        
        if project_folder_id:
            design_folder_id = ensure_folder(drive, "02_Design", project_folder_id)
            upload_file(drive, str(arch_file), design_folder_id)
            logger.log("UI Architect", "UX architecture mirrored to Google Drive.")
    except Exception as e:
        logger.log("UI Architect", f"Drive sync failed: {e}", severity="WARN")

    return {
        "ux_arch_path": str(arch_file),
        "project_budget_tokens": new_budget
    }
