from typing import List, Optional, Dict
from pydantic import BaseModel, Field # type: ignore

class BrandDNA(BaseModel):
    """
    The core strategic DNA of the brand.
    Generated by the Chief Strategy Agent.
    """
    name: str = Field(description="The agreed name of the brand.")
    tagline: str = Field(description="A punchy, memorable tagline.")
    mission: str = Field(description="The brand's core mission statement.")
    archetype: str = Field(description="The brand archetype (e.g., The Creator, The Ruler).")
    core_values: List[str] = Field(description="List of 3-5 core values.")
    target_audience: str = Field(description="Description of the primary demographic/psychographic.")
    
    # Visual Direction
    color_palette_hex: List[str] = Field(description="List of 3-5 hex codes.")
    typography_primary: str = Field(description="Name of primary font (Google Fonts).")
    typography_secondary: str = Field(description="Name of secondary font.")
    visual_style_prompt: str = Field(description="A detailed prompt describing the visual style for image generation.")

class SocialPost(BaseModel):
    platform: str
    content_type: str # Story, Post, Reel
    caption: str
    hashtags: List[str]
    image_prompt: Optional[str] = None

class ProjectContext(BaseModel):
    """
    Structured context extracted from the kickoff transcript.
    """
    project_name: str = Field(description="Name of the project.")
    client_goals: List[str] = Field(description="List of extracted client goals.")
    deliverables: List[str] = Field(description="List of specific deliverables.")
    hard_deadlines: Dict[str, str] = Field(description="Dictionary of deadlines (Item -> Date).")
    budget_hint: Optional[str] = Field(description="Any mentioned budget constraints.")
    missing_info: List[str] = Field(default_factory=list, description="Critical info detected as missing.")
    clarifying_questions: List[str] = Field(default_factory=list, description="Questions generated for the human director.")
    project_type: str = Field(default="Unknown", description="Classified project type.")

class Mission(BaseModel):
    """
    A specific mission assigned to an agent or a group of agents.
    """
    name: str
    status: str = "Pending" # Pending, In Progress, Completed
    completion: float = 0.0
    active_agents: List[str]
    next_step: str
    context: ProjectContext
